### ISSUE TITLE
Livescript 2.0

### ISSUE THREAD

**Issue by neersighted** [gkz/LiveScript#260]
# Livescript 2.0

Discuss Livescript 2.0 here.  Please break major components of 2.0 into separate issues.
## Progress
- [ ] Rewrite with the [Redux](https://github.com/michaelficarra/CoffeeScriptRedux) compiler, and generate a Mozilla JS AST: #262, #125 
  - Support source maps
  - Generate a Mozilla JS AST
  - Generate code from AST with `escodegen`
  - <further details from @gkz here>
- [ ] Type inference and verification: #30 
- [ ] ECMAScript 6 features: #26 
- [ ] Remove legacy features: #219 
- [ ] Overhaul Prelude.ls: gkz/prelude-ls#45
  - Extension system
  - <further details from @gkz here>
- [ ] Overhaul `slake`: #225
  - Task dependencies
  - Function-oriented: currying, piping vs inheritance, subclassing, and chaining
  - Helper functions
- [ ] Match (psuedo pattern-matching): #109 
- [ ] Github syntax highlighting: #39, github/linguist#183
- [ ] Rename NPM package 'LiveScript' to 'livescript': #261 
- [ ] Add Livescript to [CDNJS](https://github.com/cdnjs/cdnjs): #240 
- [ ] Add Prelude.ls to [CDNJS](https://github.com/cdnjs/cdnjs): gkz/prelude-ls#40
### Blocking
- None
### Major
- None
### Minor
- None
